---
title: "Exercise 9"
author: "Jonas Freimuth, 807218"
date: "15 12 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("lme4")
library("dplyr")
library("fastDummies")
```

## Task 1

```{r task_1_1}
yld_dat <- read.csv("data/Ex9_1.csv")

yld_lmer <- lmer(yield ~ (1 | geno) + (1 | env) +
                   (1 | geno : env) + (1 | rep),
                 yld_dat)

summary(yld_lmer)

```


## Task 2

```{r task_2_1}
pig_dat <- read.csv("data/Ex9_2.csv")

pig_lm <- lmer(production ~ sex + (1 | population), pig_dat)

summary(pig_lm)

varcomp <- VarCorr(pig_lm)

pop_varcomp <- as.numeric(varcomp[1])
res_varcomp <- attr(varcomp, "sc") ^ 2 
```

```{r task_2_2}
n <- nrow(pig_dat)
p <- length(unique(pig_dat$population))

y <- as.matrix(pig_dat$production)

R <- res_varcomp * diag(n)
G <- (pop_varcomp / 4) * diag(p)
Z <- as.matrix(dummy_cols(pig_dat, "population")[, 4:8])

V <- Z %*% G %*% t(Z) + R

X <- as.matrix(dummy_cols(pig_dat, "sex")[, 4:5])

BLUE <- solve(t(X) %*% solve(V) %*% X) %*% t(X) %*% solve(V) %*% y
BLUP <- G %*% t(Z) %*% solve(V) %*% (y - X %*% BLUE)
```

$\Rightarrow$ BLUE is `r round(BLUE, 2)`; BLUP is `r round(BLUP, 2)`.

## Task 3

Solve once via animal model and once via Handerson eq

### Animal model:

```{r task_3_1}
n <- 7

A <- diag(1, n, n)
A[c(1, 2), c(3, 4)] <- 0.5
A[c(5), c(6, 7)] <- 0.5
A[c(3), c(4)] <- 0.5
A[c(6), c(7)] <- 0.25
A[lower.tri(A)] <- t(A)[lower.tri(A)]

y <- c(10, 20, 35, 38, 30, 24, 42)

lambda <- 70 / 30

I <- diag(1, n, n)

H <- I + lambda * solve(A)

B <- rbind(cbind(n, matrix(1, 1, n)), cbind(matrix(1, n, 1), H))

uy <- c(sum(y), y)

r <- solve(B, uy)
```

$\Rightarrow$ The breeding values from the animal model are `r round(r[-1], 2)`.

### Handerson formulas

```{r task_3_2}
n <- 7
p <- 2 # ?

y <- c(10, 20, 35, 38, 30, 24, 42)

R <- 70 * diag(n)
G <- 30 * A
Z <- diag(n)

V <- Z %*% G %*% t(Z) + R

X <- matrix(1, n, 1)

BLUE <- solve(t(X) %*% solve(V) %*% X) %*% t(X) %*% solve(V) %*% y
BLUP <- G %*% t(Z) %*% solve(V) %*% (y - X %*% BLUE)
```

$\Rightarrow$ The breeding values from the Handerson formulas are
`r round(BLUP, 2)`.

## Task 4

```{r task_4_1}
n <- 5

A <- diag(n)

A[c(1, 2), c(3:5)] <- 0.5
A[c(3)   , c(4:5)] <- 0.5
A[c(4)   , c(5)  ] <- 0.5
A[lower.tri(A)] <- t(A)[lower.tri(A)]
A

y <- c(42, 21, 26, 35)

lambda <- 70 / 30

R <- 70 * diag(length(y))
G <- 30 * A

Z <- matrix(0, length(y), n)
Z[1, 1] <- 1
Z[2, 3] <- 1
Z[3, 4] <- 1
Z[4, 5] <- 1


V <- Z %*% G %*% t(Z) + R

X <- matrix(1, length(y), 1)

P <- solve(t(X) %*% solve(V) %*% X) %*% t(X) %*% solve(V)

BLUE <- P %*% y
BLUP <- G %*% t(Z) %*% solve(V) %*% (y - X %*% BLUE)
```
